export const LOGIN = 'login'
export const USERMESSAGE = 'user_message'
export const CLEARSTORE = 'clear_store'
export const DICTLOADING = 'dict_loading'
export const DICTFAIL = 'dict_fail'
export const DICTSUCCESS = 'dict_success'
